// Generated by CoffeeScript 1.4.0
(function() {
  var Scrheight, Scrwidth, addSpans, alphabet, body, i, numGrid, numHorGrid, numVerGrid, spanHeight, spanWidth, spanZ, _i, _ref;

  $(function() {});

  body = $('body');

  alphabet = ["A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z", "®", "©"];

  Scrwidth = document.width;

  Scrheight = document.height;

  numHorGrid = 4;

  numVerGrid = 7;

  numGrid = numHorGrid * numVerGrid;

  spanWidth = Scrwidth / numVerGrid;

  spanHeight = Scrheight / numHorGrid;

  addSpans = function(arg) {
    var coef, spanModel, value;
    coef = Math.floor(arg / alphabet.length);
    value = alphabet[i - alphabet.length * coef];
    spanModel = "<span style='width:" + (spanWidth * 0.95) + "px; height:" + spanHeight + "px; font-size:" + spanWidth + "px; line-height:" + spanHeight + "px; display:inline-block;position:relative;text-align:center;'>" + value + "</span>";
    return body.append(spanModel);
  };

  for (i = _i = 0, _ref = numGrid - 1; _i <= _ref; i = _i += 1) {
    addSpans(i);
  }

  spanZ = $('span');

  spanZ.each(function() {});

}).call(this);
