// Generated by CoffeeScript 1.4.0
(function() {
  var Scrheight, Scrwidth, addDivs, body, gridNum, i, _i;

  $(function() {});

  body = $('body');

  Scrwidth = document.width;

  Scrheight = document.height;

  gridNum = 649;

  addDivs = function(arg) {
    var divModel;
    divModel = "<div rel='" + i + "' style='width:4%; height:4%;position:relative;float:left;margin:0:padding:0;'></div>";
    return body.append(divModel);
  };

  for (i = _i = 0; _i <= gridNum; i = _i += 1) {
    addDivs(i);
  }

  (function() {
    return $('body > div').mouseover(function() {
      var currentRel;
      currentRel = $(this).attr('rel');
      return $('body').attr('rel', currentRel);
    });
  })();

}).call(this);
